# Generated by Django 4.2.4 on 2023-10-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='socio',
        ),
    ]
