# Generated by Django 4.2.4 on 2023-11-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_delete_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='actividad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Administracion.actividad'),
            preserve_default=False,
        ),
    ]
