# Generated by Django 4.2.4 on 2023-10-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroSocio', models.IntegerField(unique=True, verbose_name='Nro de Socio')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('genero', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], default=1)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('tel', models.IntegerField(verbose_name='Tel')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro', models.IntegerField(verbose_name='Nro')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto')),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
            ],
        ),
    ]
