# Generated by Django 4.2.4 on 2023-11-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='observaciones_importantes',
            field=models.TextField(max_length=100, null=True, verbose_name='Observaciones Importantes'),
        ),
    ]
