# Generated by Django 4.2.4 on 2023-11-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0003_alter_socio_observaciones_importantes'),
        ('Inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Socios.socio', verbose_name='Socio'),
        ),
    ]
