# Generated by Django 4.2.4 on 2023-10-26 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotamensual',
            options={},
        ),
        migrations.RemoveField(
            model_name='cuotamensual',
            name='pagado',
        ),
        migrations.AddField(
            model_name='cuotamensual',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='cuotamensual',
            name='fecha_pago',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cuotamensual',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Sepiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')]),
        ),
    ]
