# Generated by Django 4.2.4 on 2023-11-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0002_socio_observaciones_importantes'),
        ('Cuotas', '0004_cuotamensual_mes_pagado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuotamensual',
            unique_together={('socio', 'mes', 'ano')},
        ),
    ]
