# Generated by Django 4.2.4 on 2023-11-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0004_profesor_actividad'),
        ('Socios', '0002_socio_observaciones_importantes'),
        ('Cuotas', '0005_alter_cuotamensual_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuotaactividad',
            unique_together={('socio', 'actividad', 'mes', 'ano')},
        ),
    ]
